//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 01:55:56 PM IST 
//


package com.modetransportation.batch.model.ar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}tpCTRL"/>
 *         &lt;element ref="{}PAYLOAD"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tpCTRL",
    "payload"
})
@XmlRootElement(name = "tpDoc")
public class TpDoc {

    @XmlElement(required = true)
    protected TpCTRL tpCTRL;
    @XmlElement(name = "PAYLOAD", required = true)
    protected PAYLOAD payload;

    /**
     * Gets the value of the tpCTRL property.
     * 
     * @return
     *     possible object is
     *     {@link TpCTRL }
     *     
     */
    public TpCTRL getTpCTRL() {
        return tpCTRL;
    }

    /**
     * Sets the value of the tpCTRL property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpCTRL }
     *     
     */
    public void setTpCTRL(TpCTRL value) {
        this.tpCTRL = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link PAYLOAD }
     *     
     */
    public PAYLOAD getPAYLOAD() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAYLOAD }
     *     
     */
    public void setPAYLOAD(PAYLOAD value) {
        this.payload = value;
    }

}
