//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 01:56:39 PM IST 
//


package com.modetransportation.batch.model.ap;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LOCATION_QNAME = new QName("", "LOCATION");
    private final static QName _DocID_QNAME = new QName("", "DocID");
    private final static QName _CHARGEAMOUNT_QNAME = new QName("", "CHARGE_AMOUNT");
    private final static QName _FINANCIALPARTYEXTERNALID_QNAME = new QName("", "FINANCIAL_PARTY_EXTERNAL_ID");
    private final static QName _SenderID_QNAME = new QName("", "SenderID");
    private final static QName _CURRENCYCODE_QNAME = new QName("", "CURRENCY_CODE");
    private final static QName _DIVISION_QNAME = new QName("", "DIVISION");
    private final static QName _CARRIER_QNAME = new QName("", "CARRIER");
    private final static QName _ORIGAPINTERNAL_QNAME = new QName("", "ORIG_AP_INTERNAL");
    private final static QName _BUSINESSLINE_QNAME = new QName("", "BUSINESS_LINE");
    private final static QName _ACCOUNTINGDATE_QNAME = new QName("", "ACCOUNTING_DATE");
    private final static QName _CHARGETYPECODE_QNAME = new QName("", "CHARGE_TYPE_CODE");
    private final static QName _CHARGETYPE_QNAME = new QName("", "CHARGE_TYPE");
    private final static QName _ORIGINCOUNTRY_QNAME = new QName("", "ORIGIN_COUNTRY");
    private final static QName _TASK_QNAME = new QName("", "TASK");
    private final static QName _PROJECT_QNAME = new QName("", "PROJECT");
    private final static QName _DUEDATE_QNAME = new QName("", "DUE_DATE");
    private final static QName _TERMS_QNAME = new QName("", "TERMS");
    private final static QName _SHIPMENTREFERENCE_QNAME = new QName("", "SHIPMENT_REFERENCE");
    private final static QName _INVOICENUMBER_QNAME = new QName("", "INVOICE_NUMBER");
    private final static QName _MASTERBLAWBNUMBER_QNAME = new QName("", "MASTER_BLAWB_NUMBER");
    private final static QName _HOUSEBLAWBNUMBER_QNAME = new QName("", "HOUSE_BLAWB_NUMBER");
    private final static QName _TYPEOFMOVE_QNAME = new QName("", "TYPE_OF_MOVE");
    private final static QName _GLACCOUNT_QNAME = new QName("", "GL_ACCOUNT");
    private final static QName _TRANSACTIONTYPE_QNAME = new QName("", "TRANSACTION_TYPE");
    private final static QName _COMPANYNUMBER_QNAME = new QName("", "COMPANY_NUMBER");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PAYLOAD }
     * 
     */
    public PAYLOAD createPAYLOAD() {
        return new PAYLOAD();
    }

    /**
     * Create an instance of {@link APEvent }
     * 
     */
    public APEvent createACCOUNTINGEVENT() {
        return new APEvent();
    }

    /**
     * Create an instance of {@link TpDoc }
     * 
     */
    public TpDoc createTpDoc() {
        return new TpDoc();
    }

    /**
     * Create an instance of {@link TpCTRL }
     * 
     */
    public TpCTRL createTpCTRL() {
        return new TpCTRL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOCATION")
    public JAXBElement<Byte> createLOCATION(Byte value) {
        return new JAXBElement<Byte>(_LOCATION_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocID")
    public JAXBElement<String> createDocID(String value) {
        return new JAXBElement<String>(_DocID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CHARGE_AMOUNT")
    public JAXBElement<BigDecimal> createCHARGEAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CHARGEAMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FINANCIAL_PARTY_EXTERNAL_ID")
    public JAXBElement<String> createFINANCIALPARTYEXTERNALID(String value) {
        return new JAXBElement<String>(_FINANCIALPARTYEXTERNALID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SenderID")
    public JAXBElement<String> createSenderID(String value) {
        return new JAXBElement<String>(_SenderID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CURRENCY_CODE")
    public JAXBElement<String> createCURRENCYCODE(String value) {
        return new JAXBElement<String>(_CURRENCYCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DIVISION")
    public JAXBElement<Byte> createDIVISION(Byte value) {
        return new JAXBElement<Byte>(_DIVISION_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARRIER")
    public JAXBElement<String> createCARRIER(String value) {
        return new JAXBElement<String>(_CARRIER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORIG_AP_INTERNAL")
    public JAXBElement<String> createORIGAPINTERNAL(String value) {
        return new JAXBElement<String>(_ORIGAPINTERNAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BUSINESS_LINE")
    public JAXBElement<Byte> createBUSINESSLINE(Byte value) {
        return new JAXBElement<Byte>(_BUSINESSLINE_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACCOUNTING_DATE")
    public JAXBElement<XMLGregorianCalendar> createACCOUNTINGDATE(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ACCOUNTINGDATE_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CHARGE_TYPE_CODE")
    public JAXBElement<String> createCHARGETYPECODE(String value) {
        return new JAXBElement<String>(_CHARGETYPECODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CHARGE_TYPE")
    public JAXBElement<String> createCHARGETYPE(String value) {
        return new JAXBElement<String>(_CHARGETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORIGIN_COUNTRY")
    public JAXBElement<String> createORIGINCOUNTRY(String value) {
        return new JAXBElement<String>(_ORIGINCOUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TASK")
    public JAXBElement<Short> createTASK(Short value) {
        return new JAXBElement<Short>(_TASK_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROJECT")
    public JAXBElement<String> createPROJECT(String value) {
        return new JAXBElement<String>(_PROJECT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DUE_DATE")
    public JAXBElement<XMLGregorianCalendar> createDUEDATE(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DUEDATE_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TERMS")
    public JAXBElement<String> createTERMS(String value) {
        return new JAXBElement<String>(_TERMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SHIPMENT_REFERENCE")
    public JAXBElement<String> createSHIPMENTREFERENCE(String value) {
        return new JAXBElement<String>(_SHIPMENTREFERENCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INVOICE_NUMBER")
    public JAXBElement<String> createINVOICENUMBER(String value) {
        return new JAXBElement<String>(_INVOICENUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MASTER_BLAWB_NUMBER")
    public JAXBElement<String> createMASTERBLAWBNUMBER(String value) {
        return new JAXBElement<String>(_MASTERBLAWBNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOUSE_BLAWB_NUMBER")
    public JAXBElement<String> createHOUSEBLAWBNUMBER(String value) {
        return new JAXBElement<String>(_HOUSEBLAWBNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TYPE_OF_MOVE")
    public JAXBElement<String> createTYPEOFMOVE(String value) {
        return new JAXBElement<String>(_TYPEOFMOVE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GL_ACCOUNT")
    public JAXBElement<Short> createGLACCOUNT(Short value) {
        return new JAXBElement<Short>(_GLACCOUNT_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TRANSACTION_TYPE")
    public JAXBElement<String> createTRANSACTIONTYPE(String value) {
        return new JAXBElement<String>(_TRANSACTIONTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPANY_NUMBER")
    public JAXBElement<Byte> createCOMPANYNUMBER(Byte value) {
        return new JAXBElement<Byte>(_COMPANYNUMBER_QNAME, Byte.class, null, value);
    }

}
