//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 11:47:12 AM IST 
//


package com.modetransportation.batch.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EquipmentInitial"/>
 *         &lt;element ref="{}EquipmentNumber"/>
 *         &lt;element ref="{}SealNumber1" minOccurs="0"/>
 *         &lt;element ref="{}SealNumber2" minOccurs="0"/>
 *         &lt;element ref="{}SealNumber3" minOccurs="0"/>
 *         &lt;element ref="{}EquipmentTypeCode"/>
 *         &lt;element name="Contents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Content" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}QuantityShipped"/>
 *                             &lt;element ref="{}UnitOfMeasure"/>
 *                             &lt;element ref="{}Description"/>
 *                             &lt;element ref="{}GrossWeight" minOccurs="0"/>
 *                             &lt;element ref="{}NetWeight" minOccurs="0"/>
 *                             &lt;element ref="{}WeightUnit" minOccurs="0"/>
 *                             &lt;element ref="{}VolumeWeight" minOccurs="0"/>
 *                             &lt;element ref="{}Volume" minOccurs="0"/>
 *                             &lt;element ref="{}VolumeUnit" minOccurs="0"/>
 *                             &lt;element ref="{}ScheduleBNumber" minOccurs="0"/>
 *                             &lt;element ref="{}HTSNumber" minOccurs="0"/>
 *                             &lt;element ref="{}Value" minOccurs="0"/>
 *                             &lt;element ref="{}Currency" minOccurs="0"/>
 *                             &lt;element ref="{}QuantityPackagingUnits" minOccurs="0"/>
 *                             &lt;element ref="{}MasterBillDescription" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Charges" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Charge" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}ChargeType"/>
 *                             &lt;element ref="{}ChargeStatus"/>
 *                             &lt;element ref="{}InvoiceNumber"/>
 *                             &lt;element ref="{}InvoiceDate"/>
 *                             &lt;element ref="{}Terms"/>
 *                             &lt;element ref="{}DueDate"/>
 *                             &lt;element ref="{}VendorCode" minOccurs="0"/>
 *                             &lt;element ref="{}VendorName" minOccurs="0"/>
 *                             &lt;element ref="{}Comments" minOccurs="0"/>
 *                             &lt;element ref="{}CustomerCode" minOccurs="0"/>
 *                             &lt;element ref="{}CustomerName" minOccurs="0"/>
 *                             &lt;element ref="{}ChargeCode"/>
 *                             &lt;element ref="{}Description"/>
 *                             &lt;element ref="{}Basis" minOccurs="0"/>
 *                             &lt;element ref="{}QuantityInvoiced" minOccurs="0"/>
 *                             &lt;element ref="{}Rate" minOccurs="0"/>
 *                             &lt;element ref="{}ChargeAmount"/>
 *                             &lt;element ref="{}Currency"/>
 *                             &lt;element ref="{}PaymentMethod" minOccurs="0"/>
 *                             &lt;element ref="{}Division"/>
 *                             &lt;element ref="{}BusinessLine"/>
 *                             &lt;element ref="{}GL_Account"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "equipmentInitial",
    "equipmentNumber",
    "sealNumber1",
    "sealNumber2",
    "sealNumber3",
    "equipmentTypeCode",
    "contents",
    "charges"
})


@XmlRootElement(name = "Container")
public class Container {
	
	@XmlElement(name = "EquipmentInitial", required = true)
    protected String equipmentInitial;
    @XmlElement(name = "EquipmentNumber", required = true)
    protected String equipmentNumber;
    @XmlElement(name = "SealNumber1")
    protected String sealNumber1;
    @XmlElement(name = "SealNumber2")
    protected String sealNumber2;
    @XmlElement(name = "SealNumber3")
    protected String sealNumber3;
    @XmlElement(name = "EquipmentTypeCode", required = true)
    protected String equipmentTypeCode;
    @XmlElement(name = "Contents")
    protected Container.Contents contents;
    @XmlElement(name = "Charges")
    protected Container.Charges charges;

    /**
     * Gets the value of the equipmentInitial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentInitial() {
        return equipmentInitial;
    }

    /**
     * Sets the value of the equipmentInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentInitial(String value) {
        this.equipmentInitial = value;
    }

    /**
     * Gets the value of the equipmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentNumber() {
        return equipmentNumber;
    }

    /**
     * Sets the value of the equipmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentNumber(String value) {
        this.equipmentNumber = value;
    }

    /**
     * Gets the value of the sealNumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber1() {
        return sealNumber1;
    }

    /**
     * Sets the value of the sealNumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber1(String value) {
        this.sealNumber1 = value;
    }

    /**
     * Gets the value of the sealNumber2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber2() {
        return sealNumber2;
    }

    /**
     * Sets the value of the sealNumber2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber2(String value) {
        this.sealNumber2 = value;
    }

    /**
     * Gets the value of the sealNumber3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber3() {
        return sealNumber3;
    }

    /**
     * Sets the value of the sealNumber3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber3(String value) {
        this.sealNumber3 = value;
    }

    /**
     * Gets the value of the equipmentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentTypeCode() {
        return equipmentTypeCode;
    }

    /**
     * Sets the value of the equipmentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentTypeCode(String value) {
        this.equipmentTypeCode = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link Container.Contents }
     *     
     */
    public Container.Contents getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Container.Contents }
     *     
     */
    public void setContents(Container.Contents value) {
        this.contents = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link Container.Charges }
     *     
     */
    public Container.Charges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Container.Charges }
     *     
     */
    public void setCharges(Container.Charges value) {
        this.charges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Charge" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}ChargeType"/>
     *                   &lt;element ref="{}ChargeStatus"/>
     *                   &lt;element ref="{}InvoiceNumber"/>
     *                   &lt;element ref="{}InvoiceDate"/>
     *                   &lt;element ref="{}Terms"/>
     *                   &lt;element ref="{}DueDate"/>
     *                   &lt;element ref="{}VendorCode" minOccurs="0"/>
     *                   &lt;element ref="{}VendorName" minOccurs="0"/>
     *                   &lt;element ref="{}Comments" minOccurs="0"/>
     *                   &lt;element ref="{}CustomerCode" minOccurs="0"/>
     *                   &lt;element ref="{}CustomerName" minOccurs="0"/>
     *                   &lt;element ref="{}ChargeCode"/>
     *                   &lt;element ref="{}Description"/>
     *                   &lt;element ref="{}Basis" minOccurs="0"/>
     *                   &lt;element ref="{}QuantityInvoiced" minOccurs="0"/>
     *                   &lt;element ref="{}Rate" minOccurs="0"/>
     *                   &lt;element ref="{}ChargeAmount"/>
     *                   &lt;element ref="{}Currency"/>
     *                   &lt;element ref="{}PaymentMethod" minOccurs="0"/>
     *                   &lt;element ref="{}Division"/>
     *                   &lt;element ref="{}BusinessLine"/>
     *                   &lt;element ref="{}GL_Account"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "charge"
    })
    public static class Charges {

        @XmlElement(name = "Charge", required = true)
        protected List<Container.Charges.Charge> charge;

        /**
         * Gets the value of the charge property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the charge property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCharge().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Container.Charges.Charge }
         * 
         * 
         */
        public List<Container.Charges.Charge> getCharge() {
            if (charge == null) {
                charge = new ArrayList<Container.Charges.Charge>();
            }
            return this.charge;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}ChargeType"/>
         *         &lt;element ref="{}ChargeStatus"/>
         *         &lt;element ref="{}InvoiceNumber"/>
         *         &lt;element ref="{}InvoiceDate"/>
         *         &lt;element ref="{}Terms"/>
         *         &lt;element ref="{}DueDate"/>
         *         &lt;element ref="{}VendorCode" minOccurs="0"/>
         *         &lt;element ref="{}VendorName" minOccurs="0"/>
         *         &lt;element ref="{}Comments" minOccurs="0"/>
         *         &lt;element ref="{}CustomerCode" minOccurs="0"/>
         *         &lt;element ref="{}CustomerName" minOccurs="0"/>
         *         &lt;element ref="{}ChargeCode"/>
         *         &lt;element ref="{}Description"/>
         *         &lt;element ref="{}Basis" minOccurs="0"/>
         *         &lt;element ref="{}QuantityInvoiced" minOccurs="0"/>
         *         &lt;element ref="{}Rate" minOccurs="0"/>
         *         &lt;element ref="{}ChargeAmount"/>
         *         &lt;element ref="{}Currency"/>
         *         &lt;element ref="{}PaymentMethod" minOccurs="0"/>
         *         &lt;element ref="{}Division"/>
         *         &lt;element ref="{}BusinessLine"/>
         *         &lt;element ref="{}GL_Account"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chargeType",
            "chargeStatus",
            "invoiceNumber",
            "invoiceDate",
            "terms",
            "dueDate",
            "vendorCode",
            "vendorName",
            "comments",
            "customerCode",
            "customerName",
            "chargeCode",
            "description",
            "basis",
            "quantityInvoiced",
            "rate",
            "chargeAmount",
            "currency",
            "paymentMethod",
            "division",
            "businessLine",
            "glAccount"
        })
        public static class Charge {

            @XmlElement(name = "ChargeType", required = true)
            protected String chargeType;
            @XmlElement(name = "ChargeStatus", required = true)
            protected String chargeStatus;
            @XmlElement(name = "InvoiceNumber", required = true)
            protected String invoiceNumber;
            @XmlElement(name = "InvoiceDate", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar invoiceDate;
            @XmlElement(name = "Terms", required = true)
            protected String terms;
            @XmlElement(name = "DueDate", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dueDate;
            @XmlElement(name = "VendorCode")
            protected String vendorCode;
            @XmlElement(name = "VendorName")
            protected String vendorName;
            @XmlElement(name = "Comments")
            protected String comments;
            @XmlElement(name = "CustomerCode")
            protected String customerCode;
            @XmlElement(name = "CustomerName")
            protected String customerName;
            @XmlElement(name = "ChargeCode", required = true)
            protected String chargeCode;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "Basis")
            protected String basis;
            @XmlElement(name = "QuantityInvoiced")
            protected BigDecimal quantityInvoiced;
            @XmlElement(name = "Rate")
            protected BigDecimal rate;
            @XmlElement(name = "ChargeAmount", required = true)
            protected BigDecimal chargeAmount;
            @XmlElement(name = "Currency", required = true)
            protected String currency;
            @XmlElement(name = "PaymentMethod")
            protected String paymentMethod;
            @XmlElement(name = "Division", required = true)
            protected String division;
            @XmlElement(name = "BusinessLine", required = true)
            protected String businessLine;
            @XmlElement(name = "GL_Account", required = true)
            protected String glAccount;

            /**
             * Gets the value of the chargeType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargeType() {
                return chargeType;
            }

            /**
             * Sets the value of the chargeType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeType(String value) {
                this.chargeType = value;
            }

            /**
             * Gets the value of the chargeStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargeStatus() {
                return chargeStatus;
            }

            /**
             * Sets the value of the chargeStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeStatus(String value) {
                this.chargeStatus = value;
            }

            /**
             * Gets the value of the invoiceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvoiceNumber() {
                return invoiceNumber;
            }

            /**
             * Sets the value of the invoiceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvoiceNumber(String value) {
                this.invoiceNumber = value;
            }

            /**
             * Gets the value of the invoiceDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getInvoiceDate() {
                return invoiceDate;
            }

            /**
             * Sets the value of the invoiceDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setInvoiceDate(XMLGregorianCalendar value) {
                this.invoiceDate = value;
            }

            /**
             * Gets the value of the terms property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTerms() {
                return terms;
            }

            /**
             * Sets the value of the terms property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTerms(String value) {
                this.terms = value;
            }

            /**
             * Gets the value of the dueDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDueDate() {
                return dueDate;
            }

            /**
             * Sets the value of the dueDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDueDate(XMLGregorianCalendar value) {
                this.dueDate = value;
            }

            /**
             * Gets the value of the vendorCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendorCode() {
                return vendorCode;
            }

            /**
             * Sets the value of the vendorCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorCode(String value) {
                this.vendorCode = value;
            }

            /**
             * Gets the value of the vendorName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendorName() {
                return vendorName;
            }

            /**
             * Sets the value of the vendorName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorName(String value) {
                this.vendorName = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

            /**
             * Gets the value of the customerCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerCode() {
                return customerCode;
            }

            /**
             * Sets the value of the customerCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerCode(String value) {
                this.customerCode = value;
            }

            /**
             * Gets the value of the customerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerName() {
                return customerName;
            }

            /**
             * Sets the value of the customerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerName(String value) {
                this.customerName = value;
            }

            /**
             * Gets the value of the chargeCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChargeCode() {
                return chargeCode;
            }

            /**
             * Sets the value of the chargeCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeCode(String value) {
                this.chargeCode = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the basis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBasis() {
                return basis;
            }

            /**
             * Sets the value of the basis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBasis(String value) {
                this.basis = value;
            }

            /**
             * Gets the value of the quantityInvoiced property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getQuantityInvoiced() {
                return quantityInvoiced;
            }

            /**
             * Sets the value of the quantityInvoiced property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantityInvoiced(BigDecimal value) {
                this.quantityInvoiced = value;
            }

            /**
             * Gets the value of the rate property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getRate() {
                return rate;
            }

            /**
             * Sets the value of the rate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setRate(BigDecimal value) {
                this.rate = value;
            }

            /**
             * Gets the value of the chargeAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getChargeAmount() {
                return chargeAmount;
            }

            /**
             * Sets the value of the chargeAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setChargeAmount(BigDecimal value) {
                this.chargeAmount = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the paymentMethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaymentMethod() {
                return paymentMethod;
            }

            /**
             * Sets the value of the paymentMethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentMethod(String value) {
                this.paymentMethod = value;
            }

            /**
             * Gets the value of the division property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDivision() {
                return division;
            }

            /**
             * Sets the value of the division property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDivision(String value) {
                this.division = value;
            }

            /**
             * Gets the value of the businessLine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessLine() {
                return businessLine;
            }

            /**
             * Sets the value of the businessLine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLine(String value) {
                this.businessLine = value;
            }

            /**
             * Gets the value of the glAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGLAccount() {
                return glAccount;
            }

            /**
             * Sets the value of the glAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGLAccount(String value) {
                this.glAccount = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Content" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}QuantityShipped"/>
     *                   &lt;element ref="{}UnitOfMeasure"/>
     *                   &lt;element ref="{}Description"/>
     *                   &lt;element ref="{}GrossWeight" minOccurs="0"/>
     *                   &lt;element ref="{}NetWeight" minOccurs="0"/>
     *                   &lt;element ref="{}WeightUnit" minOccurs="0"/>
     *                   &lt;element ref="{}VolumeWeight" minOccurs="0"/>
     *                   &lt;element ref="{}Volume" minOccurs="0"/>
     *                   &lt;element ref="{}VolumeUnit" minOccurs="0"/>
     *                   &lt;element ref="{}ScheduleBNumber" minOccurs="0"/>
     *                   &lt;element ref="{}HTSNumber" minOccurs="0"/>
     *                   &lt;element ref="{}Value" minOccurs="0"/>
     *                   &lt;element ref="{}Currency" minOccurs="0"/>
     *                   &lt;element ref="{}QuantityPackagingUnits" minOccurs="0"/>
     *                   &lt;element ref="{}MasterBillDescription" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Contents {

        @XmlElement(name = "Content", required = true)
        protected List<Container.Contents.Content> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Container.Contents.Content }
         * 
         * 
         */
        public List<Container.Contents.Content> getContent() {
            if (content == null) {
                content = new ArrayList<Container.Contents.Content>();
            }
            return this.content;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}QuantityShipped"/>
         *         &lt;element ref="{}UnitOfMeasure"/>
         *         &lt;element ref="{}Description"/>
         *         &lt;element ref="{}GrossWeight" minOccurs="0"/>
         *         &lt;element ref="{}NetWeight" minOccurs="0"/>
         *         &lt;element ref="{}WeightUnit" minOccurs="0"/>
         *         &lt;element ref="{}VolumeWeight" minOccurs="0"/>
         *         &lt;element ref="{}Volume" minOccurs="0"/>
         *         &lt;element ref="{}VolumeUnit" minOccurs="0"/>
         *         &lt;element ref="{}ScheduleBNumber" minOccurs="0"/>
         *         &lt;element ref="{}HTSNumber" minOccurs="0"/>
         *         &lt;element ref="{}Value" minOccurs="0"/>
         *         &lt;element ref="{}Currency" minOccurs="0"/>
         *         &lt;element ref="{}QuantityPackagingUnits" minOccurs="0"/>
         *         &lt;element ref="{}MasterBillDescription" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "quantityShipped",
            "unitOfMeasure",
            "description",
            "grossWeight",
            "netWeight",
            "weightUnit",
            "volumeWeight",
            "volume",
            "volumeUnit",
            "scheduleBNumber",
            "htsNumber",
            "value",
            "currency",
            "quantityPackagingUnits",
            "masterBillDescription"
        })
        public static class Content {

            @XmlElement(name = "QuantityShipped", required = true)
            protected BigDecimal quantityShipped;
            @XmlElement(name = "UnitOfMeasure", required = true)
            protected String unitOfMeasure;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "GrossWeight")
            protected BigDecimal grossWeight;
            @XmlElement(name = "NetWeight")
            protected BigDecimal netWeight;
            @XmlElement(name = "WeightUnit")
            protected String weightUnit;
            @XmlElement(name = "VolumeWeight")
            protected BigDecimal volumeWeight;
            @XmlElement(name = "Volume")
            protected BigDecimal volume;
            @XmlElement(name = "VolumeUnit")
            protected String volumeUnit;
            @XmlElement(name = "ScheduleBNumber")
            protected String scheduleBNumber;
            @XmlElement(name = "HTSNumber")
            protected String htsNumber;
            @XmlElement(name = "Value")
            protected BigDecimal value;
            @XmlElement(name = "Currency")
            protected String currency;
            @XmlElement(name = "QuantityPackagingUnits")
            protected BigInteger quantityPackagingUnits;
            @XmlElement(name = "MasterBillDescription")
            protected String masterBillDescription;

            /**
             * Gets the value of the quantityShipped property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getQuantityShipped() {
                return quantityShipped;
            }

            /**
             * Sets the value of the quantityShipped property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantityShipped(BigDecimal value) {
                this.quantityShipped = value;
            }

            /**
             * Gets the value of the unitOfMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnitOfMeasure() {
                return unitOfMeasure;
            }

            /**
             * Sets the value of the unitOfMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnitOfMeasure(String value) {
                this.unitOfMeasure = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the grossWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getGrossWeight() {
                return grossWeight;
            }

            /**
             * Sets the value of the grossWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGrossWeight(BigDecimal value) {
                this.grossWeight = value;
            }

            /**
             * Gets the value of the netWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getNetWeight() {
                return netWeight;
            }

            /**
             * Sets the value of the netWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setNetWeight(BigDecimal value) {
                this.netWeight = value;
            }

            /**
             * Gets the value of the weightUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWeightUnit() {
                return weightUnit;
            }

            /**
             * Sets the value of the weightUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWeightUnit(String value) {
                this.weightUnit = value;
            }

            /**
             * Gets the value of the volumeWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getVolumeWeight() {
                return volumeWeight;
            }

            /**
             * Sets the value of the volumeWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setVolumeWeight(BigDecimal value) {
                this.volumeWeight = value;
            }

            /**
             * Gets the value of the volume property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getVolume() {
                return volume;
            }

            /**
             * Sets the value of the volume property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setVolume(BigDecimal value) {
                this.volume = value;
            }

            /**
             * Gets the value of the volumeUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVolumeUnit() {
                return volumeUnit;
            }

            /**
             * Sets the value of the volumeUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVolumeUnit(String value) {
                this.volumeUnit = value;
            }

            /**
             * Gets the value of the scheduleBNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScheduleBNumber() {
                return scheduleBNumber;
            }

            /**
             * Sets the value of the scheduleBNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScheduleBNumber(String value) {
                this.scheduleBNumber = value;
            }

            /**
             * Gets the value of the htsNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHTSNumber() {
                return htsNumber;
            }

            /**
             * Sets the value of the htsNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHTSNumber(String value) {
                this.htsNumber = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the quantityPackagingUnits property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getQuantityPackagingUnits() {
                return quantityPackagingUnits;
            }

            /**
             * Sets the value of the quantityPackagingUnits property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setQuantityPackagingUnits(BigInteger value) {
                this.quantityPackagingUnits = value;
            }

            /**
             * Gets the value of the masterBillDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMasterBillDescription() {
                return masterBillDescription;
            }

            /**
             * Sets the value of the masterBillDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMasterBillDescription(String value) {
                this.masterBillDescription = value;
            }

        }

    }

}
