//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 11:47:12 AM IST 
//


package com.modetransportation.batch.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CargoControlNumber_QNAME = new QName("", "CargoControlNumber");
    private final static QName _TransactionDateTime_QNAME = new QName("", "TransactionDateTime");
    private final static QName _DivisionAlpha_QNAME = new QName("", "DivisionAlpha");
    private final static QName _TransportationMethod_QNAME = new QName("", "TransportationMethod");
    private final static QName _ChargeAmount_QNAME = new QName("", "ChargeAmount");
    private final static QName _ArrivalDateTime_QNAME = new QName("", "ArrivalDateTime");
    private final static QName _DepartureLocationQualifier_QNAME = new QName("", "DepartureLocationQualifier");
    private final static QName _Currency_QNAME = new QName("", "Currency");
    private final static QName _TypeOfMove_QNAME = new QName("", "TypeOfMove");
    private final static QName _InvoiceNumber_QNAME = new QName("", "InvoiceNumber");
    private final static QName _ChargeUnit_QNAME = new QName("", "ChargeUnit");
    private final static QName _VendorName_QNAME = new QName("", "VendorName");
    private final static QName _GrossWeight_QNAME = new QName("", "GrossWeight");
    private final static QName _PartyCode_QNAME = new QName("", "PartyCode");
    private final static QName _IdCodeQualifier_QNAME = new QName("", "IdCodeQualifier");
    private final static QName _QuantityShipped_QNAME = new QName("", "QuantityShipped");
    private final static QName _Rate_QNAME = new QName("", "Rate");
    private final static QName _SealNumber3_QNAME = new QName("", "SealNumber3");
    private final static QName _ITNumber_QNAME = new QName("", "ITNumber");
    private final static QName _SealNumber2_QNAME = new QName("", "SealNumber2");
    private final static QName _SealNumber1_QNAME = new QName("", "SealNumber1");
    private final static QName _TransactionId_QNAME = new QName("", "TransactionId");
    private final static QName _CustomerReference_QNAME = new QName("", "CustomerReference");
    private final static QName _Contents_QNAME = new QName("", "Contents");
    private final static QName _Volume_QNAME = new QName("", "Volume");
    private final static QName _BookingNumber_QNAME = new QName("", "BookingNumber");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _DepartureLocation_QNAME = new QName("", "DepartureLocation");
    private final static QName _LocationName_QNAME = new QName("", "LocationName");
    private final static QName _VoyageFlightNumber_QNAME = new QName("", "VoyageFlightNumber");
    private final static QName _VolumeWeight_QNAME = new QName("", "VolumeWeight");
    private final static QName _ArrivalLocation_QNAME = new QName("", "ArrivalLocation");
    private final static QName _VendorCode_QNAME = new QName("", "VendorCode");
    private final static QName _Division_QNAME = new QName("", "Division");
    private final static QName _Charges_QNAME = new QName("", "Charges");
    private final static QName _BusinessLine_QNAME = new QName("", "BusinessLine");
    private final static QName _InvoiceDate_QNAME = new QName("", "InvoiceDate");
    private final static QName _WarehouseLocation_QNAME = new QName("", "WarehouseLocation");
    private final static QName _StateOrProvinceCode_QNAME = new QName("", "StateOrProvinceCode");
    private final static QName _SubHouseBillNumber_QNAME = new QName("", "SubHouseBillNumber");
    private final static QName _ImportDate_QNAME = new QName("", "ImportDate");
    private final static QName _TransportationTermsLocation_QNAME = new QName("", "TransportationTermsLocation");
    private final static QName _CustomerCode_QNAME = new QName("", "CustomerCode");
    private final static QName _LocationId_QNAME = new QName("", "LocationId");
    private final static QName _Routing_QNAME = new QName("", "Routing");
    private final static QName _NetWeight_QNAME = new QName("", "NetWeight");
    private final static QName _HTSNumber_QNAME = new QName("", "HTSNumber");
    private final static QName _ChargeType_QNAME = new QName("", "ChargeType");
    private final static QName _EquipmentTypeCode_QNAME = new QName("", "EquipmentTypeCode");
    private final static QName _ScheduleBNumber_QNAME = new QName("", "ScheduleBNumber");
    private final static QName _DocumentDate_QNAME = new QName("", "DocumentDate");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _ArrivalLocationQualifier_QNAME = new QName("", "ArrivalLocationQualifier");
    private final static QName _ShipmentType_QNAME = new QName("", "ShipmentType");
    private final static QName _Remarks_QNAME = new QName("", "Remarks");
    private final static QName _VolumeUnit_QNAME = new QName("", "VolumeUnit");
    private final static QName _Qualifier_QNAME = new QName("", "Qualifier");
    private final static QName _Carrier_QNAME = new QName("", "Carrier");
    private final static QName _MasterBillNumber_QNAME = new QName("", "MasterBillNumber");
    private final static QName _FIRMSCode_QNAME = new QName("", "FIRMSCode");
    private final static QName _UnitOfMeasure_QNAME = new QName("", "UnitOfMeasure");
    private final static QName _ReferenceNumber_QNAME = new QName("", "ReferenceNumber");
    private final static QName _Terms_QNAME = new QName("", "Terms");
    private final static QName _CityName_QNAME = new QName("", "CityName");
    private final static QName _Sequence_QNAME = new QName("", "Sequence");
    private final static QName _VesselName_QNAME = new QName("", "VesselName");
    private final static QName _ChargeCode_QNAME = new QName("", "ChargeCode");
    private final static QName _DeliveryDateTime_QNAME = new QName("", "DeliveryDateTime");
    private final static QName _ChargeStatus_QNAME = new QName("", "ChargeStatus");
    private final static QName _Content_QNAME = new QName("", "Content");
    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _PaymentMethod_QNAME = new QName("", "PaymentMethod");
    private final static QName _EquipmentNumber_QNAME = new QName("", "EquipmentNumber");
    private final static QName _FileNumber_QNAME = new QName("", "FileNumber");
    private final static QName _MasterBillDescription_QNAME = new QName("", "MasterBillDescription");
    private final static QName _TransactionType_QNAME = new QName("", "TransactionType");
    private final static QName _TransportationTerms_QNAME = new QName("", "TransportationTerms");
    private final static QName _MarksNumbers_QNAME = new QName("", "MarksNumbers");
    private final static QName _TransportationTermsLocationQualifier_QNAME = new QName("", "TransportationTermsLocationQualifier");
    private final static QName _PostalCode_QNAME = new QName("", "PostalCode");
    private final static QName _WeightUnit_QNAME = new QName("", "WeightUnit");
    private final static QName _Segment_QNAME = new QName("", "Segment");
    private final static QName _Basis_QNAME = new QName("", "Basis");
    private final static QName _EquipmentInitial_QNAME = new QName("", "EquipmentInitial");
    private final static QName _TransactionSetPurpose_QNAME = new QName("", "TransactionSetPurpose");
    private final static QName _PickupDateTime_QNAME = new QName("", "PickupDateTime");
    private final static QName _CustomerName_QNAME = new QName("", "CustomerName");
    private final static QName _CountryCode_QNAME = new QName("", "CountryCode");
    private final static QName _DueDate_QNAME = new QName("", "DueDate");
    private final static QName _PartyType_QNAME = new QName("", "PartyType");
    private final static QName _QuantityInvoiced_QNAME = new QName("", "QuantityInvoiced");
    private final static QName _ServiceContract_QNAME = new QName("", "ServiceContract");
    private final static QName _Comments_QNAME = new QName("", "Comments");
    private final static QName _Address2_QNAME = new QName("", "Address2");
    private final static QName _Charge_QNAME = new QName("", "Charge");
    private final static QName _Address1_QNAME = new QName("", "Address1");
    private final static QName _TypeOfService_QNAME = new QName("", "TypeOfService");
    private final static QName _QuantityPackagingUnits_QNAME = new QName("", "QuantityPackagingUnits");
    private final static QName _LocationIdQualifier_QNAME = new QName("", "LocationIdQualifier");
    private final static QName _DepartureDateTime_QNAME = new QName("", "DepartureDateTime");
    private final static QName _HouseBillNumber_QNAME = new QName("", "HouseBillNumber");
    private final static QName _GLAccount_QNAME = new QName("", "GL_Account");
    private final static QName _IdCode_QNAME = new QName("", "IdCode");
    private final static QName _Clause_QNAME = new QName("", "Clause");
    private final static QName _LocationType_QNAME = new QName("", "LocationType");
    private final static QName _OriginReference_QNAME = new QName("", "OriginReference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link Shipment.Charges }
     * 
     */
    public Shipment.Charges createShipmentCharges() {
        return new Shipment.Charges();
    }

    /**
     * Create an instance of {@link Shipment.Contents }
     * 
     */
    public Shipment.Contents createShipmentContents() {
        return new Shipment.Contents();
    }

    /**
     * Create an instance of {@link Shipment.Routing }
     * 
     */
    public Shipment.Routing createShipmentRouting() {
        return new Shipment.Routing();
    }

    /**
     * Create an instance of {@link Container.Charges }
     * 
     */
    public Container.Charges createContainerCharges() {
        return new Container.Charges();
    }

    /**
     * Create an instance of {@link Container.Contents }
     * 
     */
    public Container.Contents createContainerContents() {
        return new Container.Contents();
    }

    /**
     * Create an instance of {@link Parties }
     * 
     */
    public Parties createParties() {
        return new Parties();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Locations }
     * 
     */
    public Locations createLocations() {
        return new Locations();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Containers }
     * 
     */
    public Containers createContainers() {
        return new Containers();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Shipment.Charges.Charge }
     * 
     */
    public Shipment.Charges.Charge createShipmentChargesCharge() {
        return new Shipment.Charges.Charge();
    }

    /**
     * Create an instance of {@link Shipment.Contents.Content }
     * 
     */
    public Shipment.Contents.Content createShipmentContentsContent() {
        return new Shipment.Contents.Content();
    }

    /**
     * Create an instance of {@link Shipment.Routing.Segment }
     * 
     */
    public Shipment.Routing.Segment createShipmentRoutingSegment() {
        return new Shipment.Routing.Segment();
    }

    /**
     * Create an instance of {@link Container.Charges.Charge }
     * 
     */
    public Container.Charges.Charge createContainerChargesCharge() {
        return new Container.Charges.Charge();
    }

    /**
     * Create an instance of {@link Container.Contents.Content }
     * 
     */
    public Container.Contents.Content createContainerContentsContent() {
        return new Container.Contents.Content();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CargoControlNumber")
    public JAXBElement<String> createCargoControlNumber(String value) {
        return new JAXBElement<String>(_CargoControlNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionDateTime")
    public JAXBElement<XMLGregorianCalendar> createTransactionDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TransactionDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DivisionAlpha")
    public JAXBElement<String> createDivisionAlpha(String value) {
        return new JAXBElement<String>(_DivisionAlpha_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransportationMethod")
    public JAXBElement<String> createTransportationMethod(String value) {
        return new JAXBElement<String>(_TransportationMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeAmount")
    public JAXBElement<BigDecimal> createChargeAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ChargeAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalDateTime")
    public JAXBElement<XMLGregorianCalendar> createArrivalDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ArrivalDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepartureLocationQualifier")
    public JAXBElement<String> createDepartureLocationQualifier(String value) {
        return new JAXBElement<String>(_DepartureLocationQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TypeOfMove")
    public JAXBElement<String> createTypeOfMove(String value) {
        return new JAXBElement<String>(_TypeOfMove_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InvoiceNumber")
    public JAXBElement<String> createInvoiceNumber(String value) {
        return new JAXBElement<String>(_InvoiceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeUnit")
    public JAXBElement<String> createChargeUnit(String value) {
        return new JAXBElement<String>(_ChargeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VendorName")
    public JAXBElement<String> createVendorName(String value) {
        return new JAXBElement<String>(_VendorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GrossWeight")
    public JAXBElement<BigDecimal> createGrossWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GrossWeight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartyCode")
    public JAXBElement<String> createPartyCode(String value) {
        return new JAXBElement<String>(_PartyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdCodeQualifier")
    public JAXBElement<String> createIdCodeQualifier(String value) {
        return new JAXBElement<String>(_IdCodeQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityShipped")
    public JAXBElement<BigDecimal> createQuantityShipped(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_QuantityShipped_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Rate")
    public JAXBElement<BigDecimal> createRate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Rate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SealNumber3")
    public JAXBElement<String> createSealNumber3(String value) {
        return new JAXBElement<String>(_SealNumber3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ITNumber")
    public JAXBElement<String> createITNumber(String value) {
        return new JAXBElement<String>(_ITNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SealNumber2")
    public JAXBElement<String> createSealNumber2(String value) {
        return new JAXBElement<String>(_SealNumber2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SealNumber1")
    public JAXBElement<String> createSealNumber1(String value) {
        return new JAXBElement<String>(_SealNumber1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionId")
    public JAXBElement<String> createTransactionId(String value) {
        return new JAXBElement<String>(_TransactionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerReference")
    public JAXBElement<String> createCustomerReference(String value) {
        return new JAXBElement<String>(_CustomerReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contents")
    public JAXBElement<Object> createContents(Object value) {
        return new JAXBElement<Object>(_Contents_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Volume")
    public JAXBElement<BigDecimal> createVolume(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Volume_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BookingNumber")
    public JAXBElement<String> createBookingNumber(String value) {
        return new JAXBElement<String>(_BookingNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepartureLocation")
    public JAXBElement<String> createDepartureLocation(String value) {
        return new JAXBElement<String>(_DepartureLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LocationName")
    public JAXBElement<String> createLocationName(String value) {
        return new JAXBElement<String>(_LocationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VoyageFlightNumber")
    public JAXBElement<String> createVoyageFlightNumber(String value) {
        return new JAXBElement<String>(_VoyageFlightNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VolumeWeight")
    public JAXBElement<BigDecimal> createVolumeWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_VolumeWeight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalLocation")
    public JAXBElement<String> createArrivalLocation(String value) {
        return new JAXBElement<String>(_ArrivalLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VendorCode")
    public JAXBElement<String> createVendorCode(String value) {
        return new JAXBElement<String>(_VendorCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Division")
    public JAXBElement<String> createDivision(String value) {
        return new JAXBElement<String>(_Division_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Charges")
    public JAXBElement<Object> createCharges(Object value) {
        return new JAXBElement<Object>(_Charges_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BusinessLine")
    public JAXBElement<String> createBusinessLine(String value) {
        return new JAXBElement<String>(_BusinessLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InvoiceDate")
    public JAXBElement<XMLGregorianCalendar> createInvoiceDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_InvoiceDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WarehouseLocation")
    public JAXBElement<String> createWarehouseLocation(String value) {
        return new JAXBElement<String>(_WarehouseLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StateOrProvinceCode")
    public JAXBElement<String> createStateOrProvinceCode(String value) {
        return new JAXBElement<String>(_StateOrProvinceCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubHouseBillNumber")
    public JAXBElement<String> createSubHouseBillNumber(String value) {
        return new JAXBElement<String>(_SubHouseBillNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ImportDate")
    public JAXBElement<XMLGregorianCalendar> createImportDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ImportDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransportationTermsLocation")
    public JAXBElement<Object> createTransportationTermsLocation(Object value) {
        return new JAXBElement<Object>(_TransportationTermsLocation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerCode")
    public JAXBElement<String> createCustomerCode(String value) {
        return new JAXBElement<String>(_CustomerCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LocationId")
    public JAXBElement<String> createLocationId(String value) {
        return new JAXBElement<String>(_LocationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Routing")
    public JAXBElement<Object> createRouting(Object value) {
        return new JAXBElement<Object>(_Routing_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetWeight")
    public JAXBElement<BigDecimal> createNetWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NetWeight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HTSNumber")
    public JAXBElement<String> createHTSNumber(String value) {
        return new JAXBElement<String>(_HTSNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeType")
    public JAXBElement<String> createChargeType(String value) {
        return new JAXBElement<String>(_ChargeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EquipmentTypeCode")
    public JAXBElement<String> createEquipmentTypeCode(String value) {
        return new JAXBElement<String>(_EquipmentTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScheduleBNumber")
    public JAXBElement<String> createScheduleBNumber(String value) {
        return new JAXBElement<String>(_ScheduleBNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentDate")
    public JAXBElement<XMLGregorianCalendar> createDocumentDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DocumentDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalLocationQualifier")
    public JAXBElement<String> createArrivalLocationQualifier(String value) {
        return new JAXBElement<String>(_ArrivalLocationQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipmentType")
    public JAXBElement<String> createShipmentType(String value) {
        return new JAXBElement<String>(_ShipmentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Remarks")
    public JAXBElement<String> createRemarks(String value) {
        return new JAXBElement<String>(_Remarks_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VolumeUnit")
    public JAXBElement<String> createVolumeUnit(String value) {
        return new JAXBElement<String>(_VolumeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Qualifier")
    public JAXBElement<String> createQualifier(String value) {
        return new JAXBElement<String>(_Qualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Carrier")
    public JAXBElement<String> createCarrier(String value) {
        return new JAXBElement<String>(_Carrier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MasterBillNumber")
    public JAXBElement<String> createMasterBillNumber(String value) {
        return new JAXBElement<String>(_MasterBillNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRMSCode")
    public JAXBElement<String> createFIRMSCode(String value) {
        return new JAXBElement<String>(_FIRMSCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnitOfMeasure")
    public JAXBElement<String> createUnitOfMeasure(String value) {
        return new JAXBElement<String>(_UnitOfMeasure_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferenceNumber")
    public JAXBElement<String> createReferenceNumber(String value) {
        return new JAXBElement<String>(_ReferenceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Terms")
    public JAXBElement<String> createTerms(String value) {
        return new JAXBElement<String>(_Terms_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CityName")
    public JAXBElement<String> createCityName(String value) {
        return new JAXBElement<String>(_CityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sequence")
    public JAXBElement<Integer> createSequence(Integer value) {
        return new JAXBElement<Integer>(_Sequence_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VesselName")
    public JAXBElement<String> createVesselName(String value) {
        return new JAXBElement<String>(_VesselName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeCode")
    public JAXBElement<String> createChargeCode(String value) {
        return new JAXBElement<String>(_ChargeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryDateTime")
    public JAXBElement<XMLGregorianCalendar> createDeliveryDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DeliveryDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeStatus")
    public JAXBElement<String> createChargeStatus(String value) {
        return new JAXBElement<String>(_ChargeStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Content")
    public JAXBElement<Object> createContent(Object value) {
        return new JAXBElement<Object>(_Content_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<BigDecimal> createValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Value_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaymentMethod")
    public JAXBElement<String> createPaymentMethod(String value) {
        return new JAXBElement<String>(_PaymentMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EquipmentNumber")
    public JAXBElement<String> createEquipmentNumber(String value) {
        return new JAXBElement<String>(_EquipmentNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileNumber")
    public JAXBElement<String> createFileNumber(String value) {
        return new JAXBElement<String>(_FileNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MasterBillDescription")
    public JAXBElement<String> createMasterBillDescription(String value) {
        return new JAXBElement<String>(_MasterBillDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionType")
    public JAXBElement<String> createTransactionType(String value) {
        return new JAXBElement<String>(_TransactionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransportationTerms")
    public JAXBElement<Object> createTransportationTerms(Object value) {
        return new JAXBElement<Object>(_TransportationTerms_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarksNumbers")
    public JAXBElement<String> createMarksNumbers(String value) {
        return new JAXBElement<String>(_MarksNumbers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransportationTermsLocationQualifier")
    public JAXBElement<String> createTransportationTermsLocationQualifier(String value) {
        return new JAXBElement<String>(_TransportationTermsLocationQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PostalCode")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WeightUnit")
    public JAXBElement<String> createWeightUnit(String value) {
        return new JAXBElement<String>(_WeightUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Segment")
    public JAXBElement<Object> createSegment(Object value) {
        return new JAXBElement<Object>(_Segment_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Basis")
    public JAXBElement<String> createBasis(String value) {
        return new JAXBElement<String>(_Basis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EquipmentInitial")
    public JAXBElement<String> createEquipmentInitial(String value) {
        return new JAXBElement<String>(_EquipmentInitial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionSetPurpose")
    public JAXBElement<String> createTransactionSetPurpose(String value) {
        return new JAXBElement<String>(_TransactionSetPurpose_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PickupDateTime")
    public JAXBElement<XMLGregorianCalendar> createPickupDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PickupDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountryCode")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DueDate")
    public JAXBElement<XMLGregorianCalendar> createDueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DueDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartyType")
    public JAXBElement<String> createPartyType(String value) {
        return new JAXBElement<String>(_PartyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityInvoiced")
    public JAXBElement<BigDecimal> createQuantityInvoiced(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_QuantityInvoiced_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceContract")
    public JAXBElement<String> createServiceContract(String value) {
        return new JAXBElement<String>(_ServiceContract_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Comments")
    public JAXBElement<String> createComments(String value) {
        return new JAXBElement<String>(_Comments_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Charge")
    public JAXBElement<Object> createCharge(Object value) {
        return new JAXBElement<Object>(_Charge_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TypeOfService")
    public JAXBElement<String> createTypeOfService(String value) {
        return new JAXBElement<String>(_TypeOfService_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityPackagingUnits")
    public JAXBElement<BigInteger> createQuantityPackagingUnits(BigInteger value) {
        return new JAXBElement<BigInteger>(_QuantityPackagingUnits_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LocationIdQualifier")
    public JAXBElement<String> createLocationIdQualifier(String value) {
        return new JAXBElement<String>(_LocationIdQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepartureDateTime")
    public JAXBElement<XMLGregorianCalendar> createDepartureDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartureDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HouseBillNumber")
    public JAXBElement<String> createHouseBillNumber(String value) {
        return new JAXBElement<String>(_HouseBillNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GL_Account")
    public JAXBElement<String> createGLAccount(String value) {
        return new JAXBElement<String>(_GLAccount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdCode")
    public JAXBElement<String> createIdCode(String value) {
        return new JAXBElement<String>(_IdCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Clause")
    public JAXBElement<String> createClause(String value) {
        return new JAXBElement<String>(_Clause_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LocationType")
    public JAXBElement<String> createLocationType(String value) {
        return new JAXBElement<String>(_LocationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginReference")
    public JAXBElement<String> createOriginReference(String value) {
        return new JAXBElement<String>(_OriginReference_QNAME, String.class, null, value);
    }

}
