//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 11:47:12 AM IST 
//


package com.modetransportation.batch.model;


import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PartyType"/>
 *         &lt;element ref="{}PartyCode" minOccurs="0"/>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Address1" minOccurs="0"/>
 *         &lt;element ref="{}Address2" minOccurs="0"/>
 *         &lt;element ref="{}CityName"/>
 *         &lt;element ref="{}StateOrProvinceCode" minOccurs="0"/>
 *         &lt;element ref="{}PostalCode" minOccurs="0"/>
 *         &lt;element ref="{}CountryCode" minOccurs="0"/>
 *         &lt;element ref="{}IdCode" minOccurs="0"/>
 *         &lt;element ref="{}IdCodeQualifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyType",
    "partyCode",
    "name",
    "address1",
    "address2",
    "cityName",
    "stateOrProvinceCode",
    "postalCode",
    "countryCode",
    "idCode",
    "idCodeQualifier"
})*/

@Entity
@XmlRootElement(name = "Party")
public class Party {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected int id;
	protected String partyType;
	protected String partyCode;
	protected String name;
	protected String address1;
	protected String address2;
	protected String cityName;
	protected String stateOrProvinceCode;
	protected String postalCode;
	protected String countryCode;
	protected String idCode;
	protected String idCodeQualifier;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fileNumber", nullable = false)
	protected Shipment shipment;

	
	

	public Shipment getShipment() {
		return shipment;
	}

	public void setShipment(Shipment shipment) {
		this.shipment = shipment;
	}

	/**
	 * Gets the value of the partyType property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "PartyType", required = true)
	public String getPartyType() {
		return partyType;
	}

	/**
	 * Sets the value of the partyType property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPartyType(String value) {
		this.partyType = value;
	}

	/**
	 * Gets the value of the partyCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "PartyCode")
	public String getPartyCode() {
		return partyCode;
	}

	/**
	 * Sets the value of the partyCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPartyCode(String value) {
		this.partyCode = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "Name", required = true)
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the address1 property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "Address1")
	public String getAddress1() {
		return address1;
	}

	/**
	 * Sets the value of the address1 property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setAddress1(String value) {
		this.address1 = value;
	}

	/**
	 * Gets the value of the address2 property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "Address2")
	public String getAddress2() {
		return address2;
	}

	/**
	 * Sets the value of the address2 property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setAddress2(String value) {
		this.address2 = value;
	}

	/**
	 * Gets the value of the cityName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "CityName", required = true)
	public String getCityName() {
		return cityName;
	}

	/**
	 * Sets the value of the cityName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCityName(String value) {
		this.cityName = value;
	}

	/**
	 * Gets the value of the stateOrProvinceCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "StateOrProvinceCode")
	public String getStateOrProvinceCode() {
		return stateOrProvinceCode;
	}

	/**
	 * Sets the value of the stateOrProvinceCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setStateOrProvinceCode(String value) {
		this.stateOrProvinceCode = value;
	}

	/**
	 * Gets the value of the postalCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "PostalCode")
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * Sets the value of the postalCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPostalCode(String value) {
		this.postalCode = value;
	}

	/**
	 * Gets the value of the countryCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "CountryCode")
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * Sets the value of the countryCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setCountryCode(String value) {
		this.countryCode = value;
	}

	/**
	 * Gets the value of the idCode property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "IdCode")
	public String getIdCode() {
		return idCode;
	}

	/**
	 * Sets the value of the idCode property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setIdCode(String value) {
		this.idCode = value;
	}

	/**
	 * Gets the value of the idCodeQualifier property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	@XmlElement(name = "IdCodeQualifier")
	public String getIdCodeQualifier() {
		return idCodeQualifier;
	}

	/**
	 * Sets the value of the idCodeQualifier property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setIdCodeQualifier(String value) {
		this.idCodeQualifier = value;
	}

}
