//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 11:47:12 AM IST 
//


package com.modetransportation.batch.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDate;

import com.modetransportation.batch.util.LocalDateAdapter;



@XmlRootElement(name = "Shipment")
@Entity
public class Shipment {

    protected String transactionId;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate transactionDateTime;
    protected String transactionSetPurpose;
    protected String transactionType;
    protected String shipmentType;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate documentDate;
    @Id
    protected String fileNumber;
    protected String masterBillNumber;
    protected String houseBillNumber;
    protected String subHouseBillNumber;
    protected String itNumber;
    protected String bookingNumber;
    protected String originReference;
    protected String customerReference;
    protected String cargoControlNumber;
    protected String division;
    protected String divisionAlpha;
    protected String paymentMethod;
    protected String transportationMethod;
    protected String transportationTerms;
    protected String transportationTermsLocation;
    protected String transportationTermsLocationQualifier;
    protected String typeOfMove;
    protected String typeOfService;
    protected String serviceContract;
    protected String vesselName;
    protected String voyageFlightNumber;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate pickupDateTime;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate departureDateTime;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate arrivalDateTime;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate deliveryDateTime;
    /*@Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")*/
    protected LocalDate importDate;
    protected String firmsCode;
    protected String warehouseLocation;
    @Transient
    protected References references;
    @Transient
    protected Shipment.Routing routing;
    @Transient
    protected Parties parties;
    @Transient
    protected Locations locations;
    @Transient
    protected Containers containers;
    @Transient
    protected Shipment.Contents contents;
    protected String marksNumbers;
    protected String clause;
    protected String remarks;
    @Transient
    protected Shipment.Charges charges;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shipment")
    private Set<Party> partySet = new HashSet<Party>(0); 

    
    
    public Set<Party> getPartySet() {
		return partySet;
	}

	public void setPartySet(Set<Party> partySet) {
		this.partySet = partySet;
	}

	/**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TransactionId", required = true)
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the transactionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "TransactionDateTime", required = true)
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getTransactionDateTime() {
        return transactionDateTime;
    }

    /**
     * Sets the value of the transactionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionDateTime(LocalDate value) {
        this.transactionDateTime = value;
    }

    /**
     * Gets the value of the transactionSetPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TransactionSetPurpose", required = true)
    public String getTransactionSetPurpose() {
        return transactionSetPurpose;
    }

    /**
     * Sets the value of the transactionSetPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSetPurpose(String value) {
        this.transactionSetPurpose = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TransactionType")
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the shipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "ShipmentType")
    public String getShipmentType() {
        return shipmentType;
    }

    /**
     * Sets the value of the shipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentType(String value) {
        this.shipmentType = value;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "DocumentDate")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentDate(LocalDate value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the fileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "FileNumber", required = true)
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * Sets the value of the fileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileNumber(String value) {
        this.fileNumber = value;
    }

    /**
     * Gets the value of the masterBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "MasterBillNumber", required = true)
    public String getMasterBillNumber() {
        return masterBillNumber;
    }

    /**
     * Sets the value of the masterBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterBillNumber(String value) {
        this.masterBillNumber = value;
    }

    /**
     * Gets the value of the houseBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "HouseBillNumber")
    public String getHouseBillNumber() {
        return houseBillNumber;
    }

    /**
     * Sets the value of the houseBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseBillNumber(String value) {
        this.houseBillNumber = value;
    }

    /**
     * Gets the value of the subHouseBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "SubHouseBillNumber")
    public String getSubHouseBillNumber() {
        return subHouseBillNumber;
    }

    /**
     * Sets the value of the subHouseBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubHouseBillNumber(String value) {
        this.subHouseBillNumber = value;
    }

    /**
     * Gets the value of the itNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "ITNumber")
    public String getITNumber() {
        return itNumber;
    }

    /**
     * Sets the value of the itNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITNumber(String value) {
        this.itNumber = value;
    }

    /**
     * Gets the value of the bookingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "BookingNumber")
    public String getBookingNumber() {
        return bookingNumber;
    }

    /**
     * Sets the value of the bookingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingNumber(String value) {
        this.bookingNumber = value;
    }

    /**
     * Gets the value of the originReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "OriginReference")
    public String getOriginReference() {
        return originReference;
    }

    /**
     * Sets the value of the originReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginReference(String value) {
        this.originReference = value;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "CustomerReference")
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the cargoControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "CargoControlNumber")
    public String getCargoControlNumber() {
        return cargoControlNumber;
    }

    /**
     * Sets the value of the cargoControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoControlNumber(String value) {
        this.cargoControlNumber = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "Division")
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the divisionAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "DivisionAlpha")
    public String getDivisionAlpha() {
        return divisionAlpha;
    }

    /**
     * Sets the value of the divisionAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionAlpha(String value) {
        this.divisionAlpha = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "PaymentMethod")
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the transportationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TransportationMethod")
    public String getTransportationMethod() {
        return transportationMethod;
    }

    /**
     * Sets the value of the transportationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportationMethod(String value) {
        this.transportationMethod = value;
    }

    /**
     * Gets the value of the transportationTerms property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @XmlElement(name = "TransportationTerms")
    public String getTransportationTerms() {
        return transportationTerms;
    }

    /**
     * Sets the value of the transportationTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransportationTerms(String value) {
        this.transportationTerms = value;
    }

    /**
     * Gets the value of the transportationTermsLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @XmlElement(name = "TransportationTermsLocation")
    public String getTransportationTermsLocation() {
        return transportationTermsLocation;
    }

    /**
     * Sets the value of the transportationTermsLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransportationTermsLocation(String value) {
        this.transportationTermsLocation = value;
    }

    /**
     * Gets the value of the transportationTermsLocationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TransportationTermsLocationQualifier")
    public String getTransportationTermsLocationQualifier() {
        return transportationTermsLocationQualifier;
    }

    /**
     * Sets the value of the transportationTermsLocationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportationTermsLocationQualifier(String value) {
        this.transportationTermsLocationQualifier = value;
    }

    /**
     * Gets the value of the typeOfMove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TypeOfMove")
    public String getTypeOfMove() {
        return typeOfMove;
    }

    /**
     * Sets the value of the typeOfMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfMove(String value) {
        this.typeOfMove = value;
    }

    /**
     * Gets the value of the typeOfService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "TypeOfService")
    public String getTypeOfService() {
        return typeOfService;
    }

    /**
     * Sets the value of the typeOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfService(String value) {
        this.typeOfService = value;
    }

    /**
     * Gets the value of the serviceContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "ServiceContract")
    public String getServiceContract() {
        return serviceContract;
    }

    /**
     * Sets the value of the serviceContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceContract(String value) {
        this.serviceContract = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "VesselName")
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the voyageFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "VoyageFlightNumber")
    public String getVoyageFlightNumber() {
        return voyageFlightNumber;
    }

    /**
     * Sets the value of the voyageFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyageFlightNumber(String value) {
        this.voyageFlightNumber = value;
    }

    /**
     * Gets the value of the pickupDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "PickupDateTime")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getPickupDateTime() {
        return pickupDateTime;
    }

    /**
     * Sets the value of the pickupDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickupDateTime(LocalDate value) {
        this.pickupDateTime = value;
    }

    /**
     * Gets the value of the departureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "DepartureDateTime")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getDepartureDateTime() {
        return departureDateTime;
    }

    /**
     * Sets the value of the departureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDateTime(LocalDate value) {
        this.departureDateTime = value;
    }

    /**
     * Gets the value of the arrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "ArrivalDateTime")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getArrivalDateTime() {
        return arrivalDateTime;
    }

    /**
     * Sets the value of the arrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalDateTime(LocalDate value) {
        this.arrivalDateTime = value;
    }

    /**
     * Gets the value of the deliveryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "DeliveryDateTime")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getDeliveryDateTime() {
        return deliveryDateTime;
    }

    /**
     * Sets the value of the deliveryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDateTime(LocalDate value) {
        this.deliveryDateTime = value;
    }

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @XmlElement(name = "ImportDate")
    @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
    public LocalDate getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportDate(LocalDate value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the firmsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "FIRMSCode")
    public String getFIRMSCode() {
        return firmsCode;
    }

    /**
     * Sets the value of the firmsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRMSCode(String value) {
        this.firmsCode = value;
    }

    /**
     * Gets the value of the warehouseLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "WarehouseLocation")
    public String getWarehouseLocation() {
        return warehouseLocation;
    }

    /**
     * Sets the value of the warehouseLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseLocation(String value) {
        this.warehouseLocation = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link References }
     *     
     */
    @XmlElement(name = "References")
    public References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link References }
     *     
     */
    public void setReferences(References value) {
        this.references = value;
    }

    /**
     * Gets the value of the routing property.
     * 
     * @return
     *     possible object is
     *     {@link Shipment.Routing }
     *     
     */
    @XmlElement(name = "Routing")
    public Shipment.Routing getRouting() {
        return routing;
    }

    /**
     * Sets the value of the routing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipment.Routing }
     *     
     */
    public void setRouting(Shipment.Routing value) {
        this.routing = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link Parties }
     *     
     */
    @XmlElement(name = "Parties")
    public Parties getParties() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parties }
     *     
     */
    public void setParties(Parties value) {
        this.parties = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Locations }
     *     
     */
    @XmlElement(name = "Locations")
    public Locations getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locations }
     *     
     */
    public void setLocations(Locations value) {
        this.locations = value;
    }

    /**
     * Gets the value of the containers property.
     * 
     * @return
     *     possible object is
     *     {@link Containers }
     *     
     */
    @XmlElement(name = "Containers")
    public Containers getContainers() {
        return containers;
    }

    /**
     * Sets the value of the containers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Containers }
     *     
     */
    public void setContainers(Containers value) {
        this.containers = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link Shipment.Contents }
     *     
     */
    @XmlElement(name = "Contents")
    public Shipment.Contents getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipment.Contents }
     *     
     */
    public void setContents(Shipment.Contents value) {
        this.contents = value;
    }

    /**
     * Gets the value of the marksNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "MarksNumbers")
    public String getMarksNumbers() {
        return marksNumbers;
    }

    /**
     * Sets the value of the marksNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarksNumbers(String value) {
        this.marksNumbers = value;
    }

    /**
     * Gets the value of the clause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "Clause")
    public String getClause() {
        return clause;
    }

    /**
     * Sets the value of the clause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClause(String value) {
        this.clause = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlElement(name = "Remarks")
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link Shipment.Charges }
     *     
     */
    @XmlElement(name = "Charges")
    public Shipment.Charges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipment.Charges }
     *     
     */
    public void setCharges(Shipment.Charges value) {
        this.charges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Charge">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}ChargeType"/>
     *                   &lt;element ref="{}ChargeStatus"/>
     *                   &lt;element ref="{}InvoiceNumber" minOccurs="0"/>
     *                   &lt;element ref="{}InvoiceDate" minOccurs="0"/>
     *                   &lt;element ref="{}Terms" minOccurs="0"/>
     *                   &lt;element ref="{}DueDate" minOccurs="0"/>
     *                   &lt;element ref="{}Comments" minOccurs="0"/>
     *                   &lt;element ref="{}CustomerCode" minOccurs="0"/>
     *                   &lt;element ref="{}CustomerName" minOccurs="0"/>
     *                   &lt;element ref="{}VendorCode" minOccurs="0"/>
     *                   &lt;element ref="{}VendorName" minOccurs="0"/>
     *                   &lt;element ref="{}ChargeCode"/>
     *                   &lt;element ref="{}Description"/>
     *                   &lt;element ref="{}Basis" minOccurs="0"/>
     *                   &lt;element ref="{}QuantityInvoiced" minOccurs="0"/>
     *                   &lt;element ref="{}ChargeUnit" minOccurs="0"/>
     *                   &lt;element ref="{}Rate" minOccurs="0"/>
     *                   &lt;element ref="{}ChargeAmount" minOccurs="0"/>
     *                   &lt;element ref="{}Currency" minOccurs="0"/>
     *                   &lt;element ref="{}PaymentMethod" minOccurs="0"/>
     *                   &lt;element ref="{}Division" minOccurs="0"/>
     *                   &lt;element ref="{}BusinessLine" minOccurs="0"/>
     *                   &lt;element ref="{}GL_Account" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
 /*   @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "charge"
    })*/
    public static class Charges {

        protected List<Shipment.Charges.Charge> charge;

        /**
         * Gets the value of the charge property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the charge property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCharge().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Shipment.Charges.Charge }
         * 
         * 
         */
        @XmlElement(name = "Charge", required = true)
         public List<Shipment.Charges.Charge> getCharge() {
            if (charge == null) {
                charge = new ArrayList<Shipment.Charges.Charge>();
            }
            return this.charge;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}ChargeType"/>
         *         &lt;element ref="{}ChargeStatus"/>
         *         &lt;element ref="{}InvoiceNumber" minOccurs="0"/>
         *         &lt;element ref="{}InvoiceDate" minOccurs="0"/>
         *         &lt;element ref="{}Terms" minOccurs="0"/>
         *         &lt;element ref="{}DueDate" minOccurs="0"/>
         *         &lt;element ref="{}Comments" minOccurs="0"/>
         *         &lt;element ref="{}CustomerCode" minOccurs="0"/>
         *         &lt;element ref="{}CustomerName" minOccurs="0"/>
         *         &lt;element ref="{}VendorCode" minOccurs="0"/>
         *         &lt;element ref="{}VendorName" minOccurs="0"/>
         *         &lt;element ref="{}ChargeCode"/>
         *         &lt;element ref="{}Description"/>
         *         &lt;element ref="{}Basis" minOccurs="0"/>
         *         &lt;element ref="{}QuantityInvoiced" minOccurs="0"/>
         *         &lt;element ref="{}ChargeUnit" minOccurs="0"/>
         *         &lt;element ref="{}Rate" minOccurs="0"/>
         *         &lt;element ref="{}ChargeAmount" minOccurs="0"/>
         *         &lt;element ref="{}Currency" minOccurs="0"/>
         *         &lt;element ref="{}PaymentMethod" minOccurs="0"/>
         *         &lt;element ref="{}Division" minOccurs="0"/>
         *         &lt;element ref="{}BusinessLine" minOccurs="0"/>
         *         &lt;element ref="{}GL_Account" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
       
        @Entity
        @Table(name = "Charge")
        public static class Charge {

        	@Id
        	@GeneratedValue(strategy = GenerationType.IDENTITY)
        	private long id;
            protected String chargeType;
            protected String chargeStatus;
            protected String invoiceNumber;
            @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
            protected LocalDate invoiceDate;
            protected String terms;
            @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
            protected LocalDate dueDate;
            protected String comments;
            protected String customerCode;
            protected String customerName;
            protected String vendorCode;
            protected String vendorName;
            protected String chargeCode;
            protected String description;
            protected String basis;
            protected BigDecimal quantityInvoiced;
            protected String chargeUnit;
            protected BigDecimal rate;
            protected BigDecimal chargeAmount;
            protected String currency;
            protected String paymentMethod;
            protected String division;
            protected String businessLine;
            protected String glAccount;

            /**
             * Gets the value of the chargeType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ChargeType", required = true)
            public String getChargeType() {
                return chargeType;
            }

            /**
             * Sets the value of the chargeType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeType(String value) {
                this.chargeType = value;
            }

            /**
             * Gets the value of the chargeStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ChargeStatus", required = true)
            public String getChargeStatus() {
                return chargeStatus;
            }

            /**
             * Sets the value of the chargeStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeStatus(String value) {
                this.chargeStatus = value;
            }

            /**
             * Gets the value of the invoiceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "InvoiceNumber")
            public String getInvoiceNumber() {
                return invoiceNumber;
            }

            /**
             * Sets the value of the invoiceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvoiceNumber(String value) {
                this.invoiceNumber = value;
            }

            /**
             * Gets the value of the invoiceDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @XmlElement(name = "InvoiceDate")
            @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
            public LocalDate getInvoiceDate() {
                return invoiceDate;
            }

            /**
             * Sets the value of the invoiceDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setInvoiceDate(LocalDate value) {
                this.invoiceDate = value;
            }

            /**
             * Gets the value of the terms property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Terms")
            public String getTerms() {
                return terms;
            }

            /**
             * Sets the value of the terms property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTerms(String value) {
                this.terms = value;
            }

            /**
             * Gets the value of the dueDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @XmlElement(name = "DueDate")
            @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
            public LocalDate getDueDate() {
                return dueDate;
            }

            /**
             * Sets the value of the dueDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDueDate(LocalDate value) {
                this.dueDate = value;
            }

            /**
             * Gets the value of the comments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Comments")
            public String getComments() {
                return comments;
            }

            /**
             * Sets the value of the comments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComments(String value) {
                this.comments = value;
            }

            /**
             * Gets the value of the customerCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "CustomerCode")
            public String getCustomerCode() {
                return customerCode;
            }

            /**
             * Sets the value of the customerCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerCode(String value) {
                this.customerCode = value;
            }

            /**
             * Gets the value of the customerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "CustomerName")
            public String getCustomerName() {
                return customerName;
            }

            /**
             * Sets the value of the customerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerName(String value) {
                this.customerName = value;
            }

            /**
             * Gets the value of the vendorCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "VendorCode")
            public String getVendorCode() {
                return vendorCode;
            }

            /**
             * Sets the value of the vendorCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorCode(String value) {
                this.vendorCode = value;
            }

            /**
             * Gets the value of the vendorName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "VendorName")
            public String getVendorName() {
                return vendorName;
            }

            /**
             * Sets the value of the vendorName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorName(String value) {
                this.vendorName = value;
            }

            /**
             * Gets the value of the chargeCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ChargeCode", required = true)
            public String getChargeCode() {
                return chargeCode;
            }

            /**
             * Sets the value of the chargeCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeCode(String value) {
                this.chargeCode = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Description", required = true)
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the basis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Basis")
            public String getBasis() {
                return basis;
            }

            /**
             * Sets the value of the basis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBasis(String value) {
                this.basis = value;
            }

            /**
             * Gets the value of the quantityInvoiced property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "QuantityInvoiced")
            public BigDecimal getQuantityInvoiced() {
                return quantityInvoiced;
            }

            /**
             * Sets the value of the quantityInvoiced property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantityInvoiced(BigDecimal value) {
                this.quantityInvoiced = value;
            }

            /**
             * Gets the value of the chargeUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ChargeUnit")
            public String getChargeUnit() {
                return chargeUnit;
            }

            /**
             * Sets the value of the chargeUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChargeUnit(String value) {
                this.chargeUnit = value;
            }

            /**
             * Gets the value of the rate property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "Rate")
            public BigDecimal getRate() {
                return rate;
            }

            /**
             * Sets the value of the rate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setRate(BigDecimal value) {
                this.rate = value;
            }

            /**
             * Gets the value of the chargeAmount property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "ChargeAmount")
            public BigDecimal getChargeAmount() {
                return chargeAmount;
            }

            /**
             * Sets the value of the chargeAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setChargeAmount(BigDecimal value) {
                this.chargeAmount = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Currency")
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the paymentMethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "PaymentMethod")
            public String getPaymentMethod() {
                return paymentMethod;
            }

            /**
             * Sets the value of the paymentMethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentMethod(String value) {
                this.paymentMethod = value;
            }

            /**
             * Gets the value of the division property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Division")
            public String getDivision() {
                return division;
            }

            /**
             * Sets the value of the division property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDivision(String value) {
                this.division = value;
            }

            /**
             * Gets the value of the businessLine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "BusinessLine")
            public String getBusinessLine() {
                return businessLine;
            }

            /**
             * Sets the value of the businessLine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLine(String value) {
                this.businessLine = value;
            }

            /**
             * Gets the value of the glAccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "GL_Account")
            public String getGLAccount() {
                return glAccount;
            }

            /**
             * Sets the value of the glAccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGLAccount(String value) {
                this.glAccount = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Content">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}QuantityShipped"/>
     *                   &lt;element ref="{}UnitOfMeasure"/>
     *                   &lt;element ref="{}Description"/>
     *                   &lt;element ref="{}GrossWeight" minOccurs="0"/>
     *                   &lt;element ref="{}NetWeight" minOccurs="0"/>
     *                   &lt;element ref="{}WeightUnit" minOccurs="0"/>
     *                   &lt;element ref="{}VolumeWeight" minOccurs="0"/>
     *                   &lt;element ref="{}Volume" minOccurs="0"/>
     *                   &lt;element ref="{}VolumeUnit" minOccurs="0"/>
     *                   &lt;element ref="{}ScheduleBNumber" minOccurs="0"/>
     *                   &lt;element ref="{}HTSNumber" minOccurs="0"/>
     *                   &lt;element ref="{}Value" minOccurs="0"/>
     *                   &lt;element ref="{}Currency" minOccurs="0"/>
     *                   &lt;element ref="{}QuantityPackagingUnits" minOccurs="0"/>
     *                   &lt;element ref="{}MasterBillDescription" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   /* @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })*/
    public static class Contents {

        
        protected Shipment.Contents.Content content;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link Shipment.Contents.Content }
         *     
         */
        
        @XmlElement(name = "Content", required = true)
        public Shipment.Contents.Content getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link Shipment.Contents.Content }
         *     
         */
        public void setContent(Shipment.Contents.Content value) {
            this.content = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}QuantityShipped"/>
         *         &lt;element ref="{}UnitOfMeasure"/>
         *         &lt;element ref="{}Description"/>
         *         &lt;element ref="{}GrossWeight" minOccurs="0"/>
         *         &lt;element ref="{}NetWeight" minOccurs="0"/>
         *         &lt;element ref="{}WeightUnit" minOccurs="0"/>
         *         &lt;element ref="{}VolumeWeight" minOccurs="0"/>
         *         &lt;element ref="{}Volume" minOccurs="0"/>
         *         &lt;element ref="{}VolumeUnit" minOccurs="0"/>
         *         &lt;element ref="{}ScheduleBNumber" minOccurs="0"/>
         *         &lt;element ref="{}HTSNumber" minOccurs="0"/>
         *         &lt;element ref="{}Value" minOccurs="0"/>
         *         &lt;element ref="{}Currency" minOccurs="0"/>
         *         &lt;element ref="{}QuantityPackagingUnits" minOccurs="0"/>
         *         &lt;element ref="{}MasterBillDescription" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
    /*    @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "quantityShipped",
            "unitOfMeasure",
            "description",
            "grossWeight",
            "netWeight",
            "weightUnit",
            "volumeWeight",
            "volume",
            "volumeUnit",
            "scheduleBNumber",
            "htsNumber",
            "value",
            "currency",
            "quantityPackagingUnits",
            "masterBillDescription"
        })*/
        @Entity
        @Table(name = "Content")
        public static class Content {
        	
        	@Id
        	@GeneratedValue(strategy = GenerationType.IDENTITY)
        	private long id;
            protected BigDecimal quantityShipped;
            protected String unitOfMeasure;
            protected String description;
            protected BigDecimal grossWeight;
            protected BigDecimal netWeight;
            protected String weightUnit;
            protected BigDecimal volumeWeight;
            protected BigDecimal volume;
            protected String volumeUnit;
            protected String scheduleBNumber;
            protected String htsNumber;
            protected BigDecimal value;
            protected String currency;
            protected BigInteger quantityPackagingUnits;
            protected String masterBillDescription;

            /**
             * Gets the value of the quantityShipped property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "QuantityShipped", required = true)
            public BigDecimal getQuantityShipped() {
                return quantityShipped;
            }

            /**
             * Sets the value of the quantityShipped property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantityShipped(BigDecimal value) {
                this.quantityShipped = value;
            }

            /**
             * Gets the value of the unitOfMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "UnitOfMeasure", required = true)
            public String getUnitOfMeasure() {
                return unitOfMeasure;
            }

            /**
             * Sets the value of the unitOfMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnitOfMeasure(String value) {
                this.unitOfMeasure = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Description", required = true)
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the grossWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "GrossWeight")
            public BigDecimal getGrossWeight() {
                return grossWeight;
            }

            /**
             * Sets the value of the grossWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGrossWeight(BigDecimal value) {
                this.grossWeight = value;
            }

            /**
             * Gets the value of the netWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "NetWeight")
            public BigDecimal getNetWeight() {
                return netWeight;
            }

            /**
             * Sets the value of the netWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setNetWeight(BigDecimal value) {
                this.netWeight = value;
            }

            /**
             * Gets the value of the weightUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "WeightUnit")
            public String getWeightUnit() {
                return weightUnit;
            }

            /**
             * Sets the value of the weightUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWeightUnit(String value) {
                this.weightUnit = value;
            }

            /**
             * Gets the value of the volumeWeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "VolumeWeight")
            public BigDecimal getVolumeWeight() {
                return volumeWeight;
            }

            /**
             * Sets the value of the volumeWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setVolumeWeight(BigDecimal value) {
                this.volumeWeight = value;
            }

            /**
             * Gets the value of the volume property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "Volume")
            public BigDecimal getVolume() {
                return volume;
            }

            /**
             * Sets the value of the volume property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setVolume(BigDecimal value) {
                this.volume = value;
            }

            /**
             * Gets the value of the volumeUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "VolumeUnit")
            public String getVolumeUnit() {
                return volumeUnit;
            }

            /**
             * Sets the value of the volumeUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVolumeUnit(String value) {
                this.volumeUnit = value;
            }

            /**
             * Gets the value of the scheduleBNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ScheduleBNumber")
            public String getScheduleBNumber() {
                return scheduleBNumber;
            }

            /**
             * Sets the value of the scheduleBNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScheduleBNumber(String value) {
                this.scheduleBNumber = value;
            }

            /**
             * Gets the value of the htsNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "HTSNumber")
            public String getHTSNumber() {
                return htsNumber;
            }

            /**
             * Sets the value of the htsNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHTSNumber(String value) {
                this.htsNumber = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            @XmlElement(name = "Value")
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Currency")
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the quantityPackagingUnits property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            @XmlElement(name = "QuantityPackagingUnits")
            public BigInteger getQuantityPackagingUnits() {
                return quantityPackagingUnits;
            }

            /**
             * Sets the value of the quantityPackagingUnits property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setQuantityPackagingUnits(BigInteger value) {
                this.quantityPackagingUnits = value;
            }

            /**
             * Gets the value of the masterBillDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "MasterBillDescription")
            public String getMasterBillDescription() {
                return masterBillDescription;
            }

            /**
             * Sets the value of the masterBillDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMasterBillDescription(String value) {
                this.masterBillDescription = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Segment">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}Sequence"/>
     *                   &lt;element ref="{}Carrier" minOccurs="0"/>
     *                   &lt;element ref="{}VesselName" minOccurs="0"/>
     *                   &lt;element ref="{}VoyageFlightNumber" minOccurs="0"/>
     *                   &lt;element ref="{}DepartureLocation"/>
     *                   &lt;element ref="{}DepartureLocationQualifier"/>
     *                   &lt;element ref="{}DepartureDateTime"/>
     *                   &lt;element ref="{}ArrivalLocation"/>
     *                   &lt;element ref="{}ArrivalLocationQualifier"/>
     *                   &lt;element ref="{}ArrivalDateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   /* @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segment"
    })*/
    public static class Routing {

        protected List<Shipment.Routing.Segment> segment;

        /**
         * Gets the value of the segment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the segment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Shipment.Routing.Segment }
         * 
         * 
         */
        @XmlElement(name = "Segment", required = true)
        public List<Shipment.Routing.Segment> getSegment() {
            if (segment == null) {
                segment = new ArrayList<Shipment.Routing.Segment>();
            }
            return this.segment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}Sequence"/>
         *         &lt;element ref="{}Carrier" minOccurs="0"/>
         *         &lt;element ref="{}VesselName" minOccurs="0"/>
         *         &lt;element ref="{}VoyageFlightNumber" minOccurs="0"/>
         *         &lt;element ref="{}DepartureLocation"/>
         *         &lt;element ref="{}DepartureLocationQualifier"/>
         *         &lt;element ref="{}DepartureDateTime"/>
         *         &lt;element ref="{}ArrivalLocation"/>
         *         &lt;element ref="{}ArrivalLocationQualifier"/>
         *         &lt;element ref="{}ArrivalDateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
      /*  @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sequence",
            "carrier",
            "vesselName",
            "voyageFlightNumber",
            "departureLocation",
            "departureLocationQualifier",
            "departureDateTime",
            "arrivalLocation",
            "arrivalLocationQualifier",
            "arrivalDateTime"
        })*/
        @Entity
        @Table(name = "Segment")
        public static class Segment {
        	
        	@Id
        	@GeneratedValue(strategy = GenerationType.IDENTITY)
        	private long id;
            protected int sequence;
            protected String carrier;
            protected String vesselName;
            protected String voyageFlightNumber;
            protected String departureLocation;
            protected String departureLocationQualifier;
            @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
            protected LocalDate departureDateTime;
            protected String arrivalLocation;
            protected String arrivalLocationQualifier;
            @Type(type="org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
            protected LocalDate arrivalDateTime;

            /**
             * Gets the value of the sequence property.
             * 
             */
            @XmlElement(name = "Sequence")
            public int getSequence() {
                return sequence;
            }

            /**
             * Sets the value of the sequence property.
             * 
             */
            public void setSequence(int value) {
                this.sequence = value;
            }

            /**
             * Gets the value of the carrier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "Carrier")
            public String getCarrier() {
                return carrier;
            }

            /**
             * Sets the value of the carrier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCarrier(String value) {
                this.carrier = value;
            }

            /**
             * Gets the value of the vesselName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "VesselName")
            public String getVesselName() {
                return vesselName;
            }

            /**
             * Sets the value of the vesselName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVesselName(String value) {
                this.vesselName = value;
            }

            /**
             * Gets the value of the voyageFlightNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "VoyageFlightNumber")
            public String getVoyageFlightNumber() {
                return voyageFlightNumber;
            }

            /**
             * Sets the value of the voyageFlightNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVoyageFlightNumber(String value) {
                this.voyageFlightNumber = value;
            }

            /**
             * Gets the value of the departureLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "DepartureLocation", required = true)
            public String getDepartureLocation() {
                return departureLocation;
            }

            /**
             * Sets the value of the departureLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartureLocation(String value) {
                this.departureLocation = value;
            }

            /**
             * Gets the value of the departureLocationQualifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "DepartureLocationQualifier", required = true)
            public String getDepartureLocationQualifier() {
                return departureLocationQualifier;
            }

            /**
             * Sets the value of the departureLocationQualifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDepartureLocationQualifier(String value) {
                this.departureLocationQualifier = value;
            }

            /**
             * Gets the value of the departureDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @XmlElement(name = "DepartureDateTime", required = true)
            @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
            public LocalDate getDepartureDateTime() {
                return departureDateTime;
            }

            /**
             * Sets the value of the departureDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDepartureDateTime(LocalDate value) {
                this.departureDateTime = value;
            }

            /**
             * Gets the value of the arrivalLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ArrivalLocation", required = true)
            public String getArrivalLocation() {
                return arrivalLocation;
            }

            /**
             * Sets the value of the arrivalLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArrivalLocation(String value) {
                this.arrivalLocation = value;
            }

            /**
             * Gets the value of the arrivalLocationQualifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @XmlElement(name = "ArrivalLocationQualifier", required = true)
            public String getArrivalLocationQualifier() {
                return arrivalLocationQualifier;
            }

            /**
             * Sets the value of the arrivalLocationQualifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArrivalLocationQualifier(String value) {
                this.arrivalLocationQualifier = value;
            }

            /**
             * Gets the value of the arrivalDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @XmlElement(name = "ArrivalDateTime", required = true)
            @XmlJavaTypeAdapter(type = LocalDate.class, value = LocalDateAdapter.class)
            public LocalDate getArrivalDateTime() {
                return arrivalDateTime;
            }

            /**
             * Sets the value of the arrivalDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setArrivalDateTime(LocalDate value) {
                this.arrivalDateTime = value;
            }

        }

    }

}
